"""
Portfolio Impact — computes total Sarpen portfolio impact from equity
exposures (IBOV, SMAL-IBOV spread) and options returns.

All functions are pure: no hidden state, no I/O.
"""

from __future__ import annotations

from typing import Dict


def compute_portfolio_impact(
    ibov_move_pct: float,
    smal_ibov_spread_move: float,
    beta_ibov: float,
    beta_spread: float,
    options_return_pct: float = 0.0,
) -> Dict[str, float]:
    """
    Compute the total portfolio impact for the Sarpen portfolio.

    The equity component is modelled as a two-factor exposure:

        equity_impact = beta_ibov * ibov_move_pct
                      + beta_spread * smal_ibov_spread_move

    The total portfolio impact adds the return generated by options:

        total_impact = equity_impact + options_return_pct

    All values are expressed in percentage points (e.g. -0.05 means -5 %).

    Parameters
    ----------
    ibov_move_pct:
        Percentage movement of the IBOV index (e.g. -0.05 for -5 %).
    smal_ibov_spread_move:
        Movement of the spread between SMAL and IBOV indices
        (e.g. 0.02 means SMAL outperformed IBOV by 2 pp).
    beta_ibov:
        Portfolio beta to the IBOV index.
    beta_spread:
        Portfolio beta to the SMAL-IBOV spread.
    options_return_pct:
        Return contribution from the options hedge book expressed as a
        percentage of the portfolio (e.g. 0.01 for +1 %).  Defaults to 0.

    Returns
    -------
    dict with keys:
        ibov_impact         — beta_ibov * ibov_move_pct
        spread_impact       — beta_spread * smal_ibov_spread_move
        equity_impact       — ibov_impact + spread_impact
        options_return_pct  — as provided
        total_impact        — equity_impact + options_return_pct
    """
    ibov_impact = beta_ibov * ibov_move_pct
    spread_impact = beta_spread * smal_ibov_spread_move
    equity_impact = ibov_impact + spread_impact
    total_impact = equity_impact + options_return_pct

    return {
        "ibov_impact": ibov_impact,
        "spread_impact": spread_impact,
        "equity_impact": equity_impact,
        "options_return_pct": options_return_pct,
        "total_impact": total_impact,
    }
